service: testing-serverless-framework

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, 'sa-east-1'}

  logRetentionInDays: 3
  deploymentBucket: serverless-framework-deployment-bucket-${opt:stage, self:provider.stage}
  
  stackTags:
    script: "cloudformation"
    project: "save-msgs"
    github: "gianaalmeida/serverless-framework"

  environment:
    DYNAMODB_TABLE: !Ref table

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - !GetAtt table.Arn


package:
  patterns:
    - handler.py


functions:
  hello:
    handler: handler.hello
    description: 'Função lambda que monitora um tópico SNS. Quando este recebe uma mensagem, a função a armazena em um banco de dados'
    events:
      - sns: topic-${opt:stage, self:provider.stage}

    environment:
      DYNAMODB_TABLE: !Ref table

resources:
  Resources:
    table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: table-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
